const mongoose = require("mongoose");

const userId = mongoose.Types.ObjectId();
const foodId = mongoose.Types.ObjectId();
const mealId = mongoose.Types.ObjectId();

const data = {
  user: [
    {
      id: userId,
      email: "ajla@gmail.com",
      password: "ajla123",
      role: "admin",
    },
    {
      id: userId,
      email: "ejla@gmail.com",
      password: "ejla123",
      role: "regular",
    },
    {
      id: userId,
      email: "mahir@gmail.com",
      password: "mahir123",
      role: "regular",
    },
    {
      id: userId,
      email: "arman@gmail.com",
      password: "arman123",
      role: "regular",
    },
  ],
  food: [
    {
      id: foodId,
      name: "Bijeli pšenični hljeb",
      image: "slika",
      serving_size: "100",
      calories: "280",
      proteins: "6.8",
      carbs: "57.5",
      fat: "0.5",
    },
    {
      id: foodId,
      name: "Mlijeko",
      image: "slika",
      serving_size: "100",
      calories: "57",
      proteins: "3.3",
      carbs: "4.7",
      fat: "2.8",
    },
    {
      id: foodId,
      name: "Jogurt",
      image: "slika",
      serving_size: "100",
      calories: "48",
      proteins: "4",
      carbs: "4.7",
      fat: "3.7",
    },
    {
      id: foodId,
      name: "Zobene pahuljice",
      image: "slika",
      serving_size: "100",
      calories: "372",
      proteins: "13.5",
      carbs: "58.7",
      fat: "7",
    },
    {
      id: foodId,
      name: "Riža",
      image: "slika",
      serving_size: "100",
      calories: "343",
      proteins: "7.5",
      carbs: "79.5",
      fat: "0.5",
    },
    {
      id: foodId,
      name: "Cijelo jaje",
      image: "slika",
      serving_size: "100",
      calories: "143",
      proteins: "13",
      carbs: "1",
      fat: "10",
    },
    {
      id: foodId,
      name: "Žumanjak",
      image: "slika",
      serving_size: "100",
      calories: "317",
      proteins: "16",
      carbs: "4",
      fat: "27",
    },
    {
      id: foodId,
      name: "Bjelanjak",
      image: "slika",
      serving_size: "100",
      calories: "48",
      proteins: "11",
      carbs: "1",
      fat: "0",
    },
  ],
  meals: [
    {
      id: mealId,
      food_id: mongoose.Types.ObjectId(),
      user_id:mongoose.Types.ObjectId(),
      serving_size: "200",
      calories: "45",
      food_mealsId: foodId,
    },
    {
      id: mealId,
      food_id: mongoose.Types.ObjectId(),
      user_id:mongoose.Types.ObjectId(),
      serving_size: "400",
      calories: "1280",
      food_mealsId: foodId,
    },
    {
      id: mealId,
      food_id: mongoose.Types.ObjectId(),
      user_id:mongoose.Types.ObjectId(),
      serving_size: "700",
      calories: "1455",
      food_mealsId: foodId,
    },
    {
      id: mealId,
      food_id: mongoose.Types.ObjectId(),
      user_id:mongoose.Types.ObjectId(),
      serving_size: "700",
      calories: "1455",
      food_mealsId: foodId,
    },
    {
      id: mealId,
      food_id: mongoose.Types.ObjectId(),
      user_id:mongoose.Types.ObjectId(),
      serving_size: "800",
      calories: "1655",
      food_mealsId: foodId,
    },
  ],
};

module.exports = data;
